#!/usr/bin/env bash
# a script to install nginx server

# installing Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Ensure Nginx is running
sudo service nginx start

#redirection
cat > /tmp/redirect_config <<EOL
server {
    listen 80;
    server_name 100.25.169.182;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

sudo mv /tmp/redirect_config /etc/nginx/sites-available/redirect

sudo nginx -t

# Restart Nginx
sudo service nginx restart
