#!/usr/bin/env bash
# a script to install nginx server

# installing Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Ensure Nginx is running
sudo service nginx start

# Configure Nginx to listen on port 80
sudo sed -i '/listen 80 default_server;/c\
server {\
    listen 80;\
    server_name 100.25.169.182;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }\
 }' /etc/nginx/sites-available/default

sudo nginx -t

# Restart Nginx
sudo service nginx restart
