#!/usr/bin/env bash
# a script to install nginx server and configure custom 404 page

# Installing Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Ensure Nginx is running
sudo service nginx start

# Create a custom 404 page
echo '<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'\''est pas une page.</p>
</body>
</html>' | sudo tee /usr/share/nginx/html/404.html

# Create a custom 404 page configuration
echo 'server {
    listen 80 default_server;
    server_name 100.25.169.182;
    error_page 404 /404.html;
     location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}' | sudo tee /etc/nginx/sites-available/custom_404
# Enable the custom 404 page configuration
sudo ln -s /etc/nginx/sites-available/404 /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx reload
