#!/usr/bin/env bash
# creating a custom header

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# code to redirect a specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.afriyie.tech permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#syntax errors test
sudo nginx -t

#reloading the server
sudo service nginx restart
