#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get -y install nginx

# the firewall is configured to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# a directory for web content is created
sudo mkdir -p /var/www/html

# permissions are set to allow easy file creation in the directory
sudo chmod -R 755 /var/www

# an index page with the text "Hello World!" is created
echo 'Hello World!' | sudo tee /var/www/html/index.html

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to add the custom header and perform a rewrite for a specific page (/redirect_me)
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.afriyie.tech permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Configure Nginx to use the custom 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart after changes
sudo service nginx restart

