#!/usr/bin/env bash
#Installs the HAProxy with the following configurations
#management is enabled via the init script
#the requests are distributed using a round-robin algorithm.

# Update the package list
sudo apt-get update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  afriyie-frontend
        bind *:80
        mode http
        default_backend afriyie-backend
backend afriyie-backend
        balance roundrobin
        server 397815-web-01 52.91.157.33 check
        server 397815-web-02 3.85.148.37 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
