#!/usr/bin/env bash
# a script to Install and configure HAproxy on my lb-01 server

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy


# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original


# Create a new HAProxy configuration file
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 ${STUDENT_ID}-web-01:80 check
    server web-02 ${STUDENT_ID}-web-02:80 check
EOL

# Restart HAProxy to apply the configuration
sudo service haproxy restart

# Verify the status of HAProxy
sudo service haproxy status
