#!/usr/bin/env bash
# a Bash script that configures a server to
# Nginx installation from listening on port 80

# Existing symbolic link to default configuration is removed
sudo rm -f /etc/nginx/sites-enabled/default

# A new symbolic link to the default configuration is created
sudo ln -s -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
