#!/usr/bin/env bash
# a bash script for fizzbuzz

count=1
until ((count >= 100))
do
    if ((count % 15 == 0))
    then 
        echo "FizzBuzz"
    elif ((count % 3 == 0))
    then
        echo "Fizz"
    elif ((count % 5 == 0))
    then
        echo "Buzz"
    else
        echo $count
    fi
    ((count++))
done
