#!/usr/bin/env bash
#Bash script that list files in the current directory

for file in *
do
    if [ -f "$file" ] && [ ! -d "$file" ] && [[ "$file" != .* ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
