#!/usr/bin/env bash
# a script that changes my home IP

localhost_mapping="127.0.0.2 localhost"
facebook_mapping="8.8.8.8 facebook.com"

cp /etc/hosts ~/hosts.new
echo "localhost_mapping" > ~/hosts.new
echo "facebook_mapping" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
